# -*- coding: utf-8 -*-
"""movie-recommendation-system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YKeaQvxJAEm1P7134gRHfuhiGoYi1_S1
"""

import numpy as np
import pandas as pd
import ast

movies = pd.read_csv('/content/ML-Project/movie_recommendation_system/tmdb_5000_movies.csv')
credits = pd.read_csv('/content/ML-Project/movie_recommendation_system/tmdb_5000_credits.csv')

movies.head()

credits.head(1)

movies = movies.merge(credits,on='title')

movies.head(1)

#genres
#id
#keywords
#title
#overview
#cast
#crew
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

movies.info()

movies.head()

movies.isnull().sum()

movies.dropna(inplace=True)

movies.duplicated().sum()

movies.iloc[0].genres

# [{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]
# ['Action', 'Adventure', 'Fantasy', 'Science Fiction']

def convert(obj):
  L = []
  if isinstance(obj, str) and obj.startswith('[') and obj.endswith(']'):
    for i in ast.literal_eval(obj):
      L.append(i['name'])
  return L

movies['genres'] = movies['genres'].apply(convert)

movies.head()

movies['keywords'] = movies['keywords'].apply(convert)

movies.head()

movies['cast'][0]

def convert3(obj):
  L = []
  counter = 0
  if isinstance(obj, str) and obj.startswith('[') and obj.endswith(']'):
    for i in ast.literal_eval(obj):
      if counter < 3:
        L.append(i['name'])
        counter+=1
      else:
        break
  return L

movies['cast'] = movies['cast'].apply(convert3)

movies.head()

movies['crew'][0]

def fetch_director(obj):
  L = []
  if isinstance(obj, str) and obj.startswith('[') and obj.endswith(']'):
    for i in ast.literal_eval(obj):
      if i['job'] == 'Director':
        L.append(i['name'])
        break
  return L

movies['crew'] = movies['crew'].apply(fetch_director)

movies.head()

movies['overview'][0]

movies['overview'] = movies['overview'].apply(lambda x:x.split())

movies.head()

movies['genres'] = movies['genres'].apply(lambda x: [i.replace(" ", "") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x: [i.replace(" ", "") for i in x])
movies['cast'] = movies['cast'].apply(lambda x: [i.replace(" ", "") for i in x])
movies['crew'] = movies['crew'].apply(lambda x: [i.replace(" ", "") for i in x])

movies.head()

movies['tag'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

movies.head()

new_df = movies[['movie_id','title','tag']]

new_df['tag'] = new_df['tag'].apply(lambda x: " ".join(x))

new_df.head()

new_df['tag'][0]

new_df['tag'] = new_df['tag'].apply(lambda x:x.lower())

new_df.head()

import nltk



from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

def stem(text):
  y = []

  for i in text.split():
    y.append(ps.stem(i))

  return " ".join(y)

new_df['tag'] = new_df['tag'].apply(stem)

new_df['tag'][0]

new_df['tag'][1]

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

vectors =  cv.fit_transform(new_df['tag']).toarray()

vectors

vectors[0]

cv.get_feature_names_out()

['love','loved','loving']
['love','love','love']

ps.stem('loved')

stem('in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron')

from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)

sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x:x[1])[1:6]

def recommend(movie):
  movie_index = new_df[new_df['title'] == movie].index[0]
  distances = similarity[movie_index]
  movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]

  for i in movies_list:
    print(new_df.iloc[i[0]].title)
  return

recommend('Batman Begins')

new_df.iloc[1216].title

new_df[new_df['title'] == 'Batman Begins'].index[0]